from marshmallow import Schema, fields

class NaturalDisastersSchema(Schema):
    id = fields.Int()
    Year = fields.Int()
    Seq = fields.Int()
    Glide = fields.Str()
    Disaster_Group = fields.Str()
    Disaster_Subgroup = fields.Str()
    Disaster_Type = fields.Str()
    Disaster_Subtype = fields.Str()
    Country = fields.Str()
    ISO = fields.Str()
    Region = fields.Str()
    Continent = fields.Str()
    Origin = fields.Str()
    Associated_Dis = fields.Str()
    Associated_Dis2 = fields.Str()
    Aid_Contribution = fields.Int()
    Dis_Mag_Value = fields.Int()
    Dis_Mag_Scale = fields.Str()
    Latitude = fields.Float()
    Longitude = fields.Float()
    Local_Time = fields.Time()
    Start_Year = fields.Int()
    Start_Month = fields.Int()
    Start_Day = fields.Int()
    End_Year = fields.Int()
    End_Month = fields.Int()
    End_Day = fields.Int()
    Total_Deaths = fields.Int()
    No_Injured = fields.Int()
    No_Affected = fields.Int()
    No_Homeless = fields.Int()
    Total_Affected = fields.Int()
    Insured_Damages_USD = fields.Int()
    Total_Damages_USD = fields.Int()
    CPI = fields.Float()